const URL=Deno.env.get('SUPABASE_URL')!;
const BASE=URL+'/functions/v1/rescue-command-center';
Deno.serve(async(req:Request)=>{
  if(req.method!=='GET')return new Response('method',{status:405});
  try{
    const r=await fetch(BASE,{headers:{'cache-control':'no-cache'}});
    if(!r.ok)return new Response('Command preview unavailable',{status:r.status});
    let h=await r.text();
    const patch=String.raw`
<style id="approved-dashboard-preview-style">
:root{--navy:#063B78;--blue:#0759A8;--bg:#F6F8FB;--line:#E2E8F0;--green:#079447;--orange:#F79009;--red:#D92D20;--side:244px}
body{background:var(--bg)!important}.top{height:68px!important;background:linear-gradient(90deg,#063B78,#001E5B)!important;padding:0 18px!important}.top .logo{width:46px!important;height:46px!important;border-radius:10px!important;background:transparent!important;padding:0!important}.top>#who,.top>#refresh,.top>#logout{display:none!important}.wrap{max-width:none!important;margin:0!important;padding:0!important}.stats,.card.toolbar,.layout,#dmtGlobalTeamTools{display:none!important}
#approvedHeaderRight{margin-left:auto;display:flex;align-items:center;gap:12px;color:#fff;font-size:12px}.approvedUpdated b{color:#58E58A}.approvedRefresh{width:36px;height:36px;border:0;border-radius:50%;background:#ffffff18;color:#fff;font-size:20px;cursor:pointer}.approvedCoordinator{display:flex;align-items:center;gap:7px;padding-left:10px;border-left:1px solid #ffffff33}.approvedCoordinatorDot{width:32px;height:32px;background:#fff;color:#063B78;border-radius:50%;display:grid;place-items:center;font-weight:900}.approvedMobileMenu{display:none;border:0;background:transparent;color:#fff;font-size:24px}
#approvedShell{min-height:calc(100vh - 68px);display:grid;grid-template-columns:var(--side) minmax(0,1fr)}#approvedSidebar{position:sticky;top:68px;height:calc(100vh - 68px);background:#fff;border-right:1px solid var(--line);padding:18px 14px;display:flex;flex-direction:column;z-index:1000}.sideAll,.sideItem{width:100%;border:0;border-radius:8px;padding:11px 12px;text-align:left;font-weight:700;display:flex;align-items:center;gap:10px;cursor:pointer}.sideAll{background:linear-gradient(90deg,#071B59,#082D83);color:#fff;margin-bottom:20px;font-size:15px}.sideItem{background:#fff;color:#102A4A}.sideItem:hover,.sideItem.active{background:#EEF4FF;color:#0759A8}.sideLabel{font-size:12px;font-weight:900;margin:0 0 8px 3px}.sideIcon{width:22px;text-align:center}.systemBox{margin-top:auto;border:1px solid #D9E1E8;border-radius:9px;padding:12px}.systemBox h4{margin:0 0 9px;font-size:13px}.systemRow{display:flex;justify-content:space-between;font-size:12px;padding:5px 0}.systemName:before{content:'◉';color:#0BA956;margin-right:8px}.systemOnline{color:#079447;font-weight:700}
#approvedMain{padding:14px 20px 28px}.approvedStats{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:8px;margin-bottom:12px}.statCard{background:#fff;border:1px solid var(--line);border-radius:9px;padding:11px 14px;display:flex;align-items:center;gap:11px;min-height:68px}.statIcon{font-size:21px;padding-right:11px;border-right:1px solid #E9EDF2}.statLabel{font-size:11px;color:#7B8491}.statValue{font-size:18px;font-weight:900}.cBlue{color:#175CD3}.cGreen{color:#079447}.cOrange{color:#F79009}.cRed{color:#D92D20}
.approvedTeam{background:#fff;border:1px solid #DFE5EC;border-radius:10px;overflow:hidden;margin-bottom:9px}.approvedTeamHead{height:41px;display:flex;align-items:center;gap:8px;padding:0 11px;color:#fff;font-weight:900}.approvedTeamHead .count{font-size:11px;font-weight:600}.approvedTeamTools{margin-left:auto;display:flex;gap:7px}.approvedTeamTools button{width:31px;height:29px;border:0;border-radius:6px;background:#ffffff1e;color:#fff;font-size:18px;cursor:pointer}.approvedMembers{display:grid;grid-template-columns:repeat(4,minmax(0,1fr)) 78px;gap:8px;padding:9px}.approvedMember{position:relative;border:1px solid #DFE5EC;border-radius:8px;padding:8px;display:grid;grid-template-columns:46px minmax(0,1fr) 68px;grid-template-rows:auto auto;gap:5px 8px;min-height:100px;background:#fff}.approvedPhoto,.approvedFallback{width:46px;height:46px;border-radius:50%;object-fit:cover;background:#EEF2F5}.approvedFallback{display:grid;place-items:center;color:#063B78;font-weight:900}.approvedName{font-size:12px;font-weight:900;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;padding-right:16px}.approvedOnline{font-size:9px;font-weight:900;margin-top:3px}.approvedOnline.live{color:#079447}.approvedOnline.off{color:#667085}.dot{display:inline-block;width:7px;height:7px;background:currentColor;border-radius:50%;margin-right:4px}.gpsLive{animation:blink 1.1s infinite}@keyframes blink{50%{opacity:.25;transform:scale(.72)}}.approvedMiniMap{grid-column:3;grid-row:1/3;width:68px;height:68px;aspect-ratio:1/1;border:1px solid #DDE4EA;border-radius:7px;overflow:hidden;background:#EEF2F5;z-index:1}.noGps{display:grid;place-items:center;font-size:9px;color:#667085;text-align:center}.approvedMission{grid-column:1/3;align-self:end;justify-self:start;padding:4px 7px;border-radius:5px;font-size:10px;font-weight:900}.mActive{background:#E9F8EF;color:#087443}.mReturn{background:#FFF2E3;color:#E56500}.mSafe{background:#EAF2FF;color:#175CD3}.mSos{background:#FFF0F0;color:#D92D20}.mOff{background:#F2F4F7;color:#667085}.memberMenuBtn{position:absolute;right:5px;top:4px;border:0;background:transparent;color:#102A4A;font-size:19px;cursor:pointer;z-index:12}.memberMenu{display:none;position:absolute;right:6px;top:30px;width:175px;background:#fff;border:1px solid #D9E1E8;border-radius:8px;box-shadow:0 8px 24px #0002;padding:5px;z-index:1400}.approvedMember.menuOpen .memberMenu{display:block}.memberMenu button{width:100%;border:0;background:#fff;border-radius:6px;padding:8px;text-align:left;font-size:12px;font-weight:700}.memberMenu .danger{color:#B42318}.moreCard{border:1px dashed #CAD3DD;border-radius:8px;background:#fff;display:grid;place-items:center;text-align:center;font-weight:800;min-height:100px}.moreCard b{font-size:18px}.teamCollapsed .approvedMembers{display:none}
.approvedPage{background:#fff;border:1px solid var(--line);border-radius:10px;padding:14px}.teamInfo{display:grid;grid-template-columns:1fr 1fr auto;gap:12px;align-items:center;padding:11px;border-bottom:1px solid #EDF1F4}.teamInfo:last-child{border-bottom:0}.codeBox{font-family:monospace;font-weight:900;background:#EEF4F1;padding:7px 9px;border-radius:7px;display:inline-block}.smallBtn{border:0;border-radius:7px;padding:8px 10px;font-weight:800;cursor:pointer}.lightBtn{background:#EEF2F5;color:#17324D}.blueBtn{background:#0759A8;color:#fff}
@media(max-width:1199px){.approvedMembers{grid-template-columns:repeat(3,minmax(0,1fr)) 75px}.approvedStats{overflow-x:auto;grid-template-columns:repeat(5,135px)}}@media(max-width:900px){#approvedShell{grid-template-columns:1fr}#approvedSidebar{position:fixed;left:0;top:68px;bottom:0;width:260px;height:auto;transform:translateX(-105%);transition:.2s;box-shadow:8px 0 24px #0002}.sidebarOpen #approvedSidebar{transform:translateX(0)}.approvedMobileMenu{display:block}.approvedCoordinator{display:none}.approvedMembers{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:767px){#approvedMain{padding:10px}.approvedMembers{grid-template-columns:1fr}.teamInfo{grid-template-columns:1fr}.approvedUpdated{font-size:10px}}
</style>
<script id="approved-dashboard-preview-js">(function(){
const COLORS=['#7A26A7','#0964CE','#079447','#F79009','#D92D5D','#0E7090'];let photos=new Map(),maps=[];const q=x=>document.getElementById(x);const inactive=d=>d?.approval_status==='revoked'||d?.active===false;const initials=n=>String(n||'?').trim().split(/\s+/).map(x=>x[0]||'').join('').slice(0,2).toUpperCase();const on=d=>typeof live==='function'?live(d):false;const gps=d=>!!d.last_seen_at&&Date.now()-new Date(d.last_seen_at).getTime()<180000&&d.last_lat!=null&&d.last_long!=null;const ex=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');let view='teams';
function header(){if(q('approvedHeaderRight'))return;const top=document.querySelector('.top');if(!top)return;const mb=document.createElement('button');mb.className='approvedMobileMenu';mb.textContent='☰';mb.onclick=()=>document.body.classList.toggle('sidebarOpen');top.insertBefore(mb,top.firstChild);const r=document.createElement('div');r.id='approvedHeaderRight';r.innerHTML='<div class="approvedUpdated">Last Updated: <b id="approvedUpdated">—</b></div><button class="approvedRefresh" id="approvedRefresh">↻</button><div class="approvedCoordinator"><span class="approvedCoordinatorDot">NS</span><span><b>Coordinator</b><br><span style="opacity:.8">Nepal Scouts</span></span></div>';top.appendChild(r);q('approvedRefresh').onclick=async()=>{const b=q('approvedRefresh');b.disabled=true;b.textContent='…';try{await load();stamp()}catch(e){alert(e.message)}finally{b.disabled=false;b.textContent='↻'}}}
function stamp(){if(q('approvedUpdated'))q('approvedUpdated').textContent=new Date().toLocaleDateString()+' '+new Date().toLocaleTimeString()}
function side(){return '<aside id="approvedSidebar"><button class="sideAll" data-v="teams"><span class="sideIcon">▦</span>All Teams</button><div class="sideLabel">Rescuer Menu</div><button class="sideItem" data-v="details"><span class="sideIcon">♙</span>All Rescuer Details</button><button class="sideItem" data-v="team"><span class="sideIcon">♧</span>Team Details</button><button class="sideItem" data-v="messages"><span class="sideIcon">▣</span>Messages</button><button class="sideItem" data-v="reports"><span class="sideIcon">⌁</span>Reports</button><button class="sideItem" data-v="alerts"><span class="sideIcon">♢</span>Alerts</button><button class="sideItem" data-v="settings"><span class="sideIcon">⚙</span>Settings</button><div class="systemBox"><h4>System Status</h4>'+['GPS Tracking','Server','Database','Notifications'].map(x=>'<div class="systemRow"><span class="systemName">'+x+'</span><span class="systemOnline">Online</span></div>').join('')+'</div></aside>'}
function stats(){const a=data.devices||[];const vals=[['♟','Total Rescuers',a.length,'cBlue'],['●','Online',a.filter(on).length,'cGreen'],['⚑','In Mission',a.filter(d=>d.mission_status==='active').length,'cOrange'],['◆','Safe',a.filter(d=>d.mission_status==='safe').length,'cBlue'],['▲','SOS',a.filter(d=>d.sos||d.mission_status==='sos').length,'cRed']];return '<div class="approvedStats">'+vals.map(x=>'<div class="statCard"><div class="statIcon '+x[3]+'">'+x[0]+'</div><div><div class="statLabel">'+x[1]+'</div><div class="statValue '+x[3]+'">'+x[2]+'</div></div></div>').join('')+'</div>'}
function badge(d){if(d.sos||d.mission_status==='sos')return '<span class="approvedMission mSos">▲ SOS</span>';if(d.mission_status==='returning')return '<span class="approvedMission mReturn">⚑ RETURNING</span>';if(d.mission_status==='safe')return '<span class="approvedMission mSafe">◆ SAFE</span>';if(d.mission_status==='active')return '<span class="approvedMission mActive">⚑ IN MISSION</span>';return '<span class="approvedMission mOff">○ OUT OF MISSION</span>'}
function card(d){const p=photos.get(d.id);return '<article class="approvedMember" data-device="'+d.id+'">'+(p?'<img class="approvedPhoto" src="'+ex(p)+'">':'<div class="approvedFallback">'+ex(initials(d.rescuer_name))+'</div>')+'<div><div class="approvedName">'+ex(d.rescuer_name)+'</div><div class="approvedOnline '+(on(d)?'live':'off')+'"><span class="dot '+(gps(d)?'gpsLive':'')+'"></span>'+(on(d)?'ONLINE':'OFFLINE')+'</div></div><button class="memberMenuBtn">⋮</button><div class="memberMenu"><button data-profile="'+d.id+'">Full Profile</button><button data-map-profile="'+d.id+'">Map / Route</button>'+(d.approval_status==='pending'?'<button data-state="approved" data-id="'+d.id+'">Accept / Approve</button>':'')+(inactive(d)?'<button data-state="approved" data-id="'+d.id+'">Reactivate</button>':'<button data-state="revoked" data-id="'+d.id+'">Revoke</button><button class="danger" data-live-delete-profile="'+d.id+'">Delete → Inactive</button>')+'</div>'+badge(d)+'<div class="approvedMiniMap" data-map="'+d.id+'"></div></article>'}
function board(){maps.forEach(m=>{try{m.remove()}catch{}});maps=[];let h=stats();(data.teams||[]).filter(t=>t.active!==false).forEach((t,i)=>{const m=(data.devices||[]).filter(d=>d.team_id===t.id&&!inactive(d)),show=m.slice(0,4),more=Math.max(0,m.length-show.length);h+='<section class="approvedTeam" data-team="'+t.id+'"><div class="approvedTeamHead" style="background:'+COLORS[i%COLORS.length]+'"><span>♟</span><span>'+ex(t.name)+'</span><span class="count">'+m.length+' Members</span><div class="approvedTeamTools"><button data-collapse="'+t.id+'">−</button><button data-manage="'+t.id+'">＋</button><button data-delete-team="'+t.id+'">⌫</button></div></div><div class="approvedMembers">'+show.map(card).join('')+(more?'<button class="moreCard" data-manage="'+t.id+'"><span><b>+'+more+'</b><br>More</span></button>':'')+'</div></section>'});return h}
function mapsNow(){document.querySelectorAll('[data-map]').forEach(el=>{const d=(data.devices||[]).find(x=>x.id===el.dataset.map);if(!d||d.last_lat==null||typeof L==='undefined'){el.classList.add('noGps');el.textContent='No GPS';return}try{const m=L.map(el,{zoomControl:false,attributionControl:false,dragging:false,scrollWheelZoom:false,doubleClickZoom:false,boxZoom:false,keyboard:false,touchZoom:false}).setView([d.last_lat,d.last_long],14);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19}).addTo(m);L.marker([d.last_lat,d.last_long]).addTo(m);maps.push(m);setTimeout(()=>m.invalidateSize(),40)}catch{}})}
function teamPage(){return '<div class="approvedPage"><h2>Team Details</h2><div class="small" style="margin-bottom:8px">Permanent team codes and team actions are kept here instead of in the dashboard header.</div>'+(data.teams||[]).filter(t=>t.active!==false).map(t=>'<div class="teamInfo"><div><b>'+ex(t.name)+'</b><div class="small">Leader: '+ex(t.leader_name||'Not assigned')+'</div></div><div><span class="codeBox">'+ex(t.join_code_display||'No code')+'</span></div><div><button class="smallBtn lightBtn" data-copy="'+ex(t.join_code_display||'')+'">Copy Code</button> <button class="smallBtn lightBtn" data-team-export="'+t.id+'">Export</button></div></div>').join('')+'</div>'}
function draw(){const main=q('approvedMain');if(!main)return;if(view==='teams'){main.innerHTML=board();mapsNow()}else if(view==='team'){main.innerHTML=teamPage()}else if(view==='details'){const old=q('dmtAllDetailsNav');if(old){q('approvedShell').style.display='none';old.click()}else main.innerHTML='<div class="approvedPage">All Rescuer Details is preserved in the existing Command profile view.</div>'}else main.innerHTML='<div class="approvedPage"><h2>'+view[0].toUpperCase()+view.slice(1)+'</h2><p>Existing '+view+' functionality is preserved. This preview changes navigation and dashboard layout only.</p></div>';stamp()}
function shell(){const app=q('app');if(!app||q('approvedShell'))return;const s=document.createElement('div');s.id='approvedShell';s.innerHTML=side()+'<main id="approvedMain"></main>';app.appendChild(s);s.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{view=b.dataset.v;document.body.classList.remove('sidebarOpen');s.querySelectorAll('.sideItem').forEach(x=>x.classList.toggle('active',x.dataset.v===view));draw()});draw()}
async function getPhotos(){try{const p=await api('photos');photos=new Map((p.photos||[]).map(x=>[x.id,x.photo]));draw()}catch{}}
document.addEventListener('click',async e=>{const mb=e.target.closest('.memberMenuBtn');if(mb){e.stopPropagation();const c=mb.closest('.approvedMember');document.querySelectorAll('.approvedMember.menuOpen').forEach(x=>{if(x!==c)x.classList.remove('menuOpen')});c.classList.toggle('menuOpen');return}if(!e.target.closest('.approvedMember'))document.querySelectorAll('.approvedMember.menuOpen').forEach(x=>x.classList.remove('menuOpen'));const c=e.target.closest('[data-collapse]');if(c){const t=document.querySelector('.approvedTeam[data-team="'+c.dataset.collapse+'"]');t?.classList.toggle('teamCollapsed');c.textContent=t?.classList.contains('teamCollapsed')?'＋':'−';return}if(e.target.closest('[data-manage]')){view='team';draw();return}const cp=e.target.closest('[data-copy]');if(cp){try{await navigator.clipboard.writeText(cp.dataset.copy||'')}catch{}return}const del=e.target.closest('[data-delete-team]');if(del){if(!confirm('Archive this team name/code? Rescuer, GPS, mission, photo and activity records will be preserved.'))return;try{await api('delete_team',{team_id:del.dataset.deleteTeam});await load()}catch(x){alert(x.message)}}},true);
const oldRender=typeof render==='function'?render:null;if(oldRender)render=function(){oldRender();setTimeout(()=>{shell();draw();stamp()},0)};header();setTimeout(()=>{shell();getPhotos();stamp()},350);
})();</script>`;
    h=h.replace('</body>',patch+'</body>');
    return new Response(h,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store','access-control-allow-origin':'*'}})
  }catch(e){console.error(e);return new Response('Command preview unavailable',{status:500})}
});
