import { createClient } from 'npm:@supabase/supabase-js@2.102.0'
const URL=Deno.env.get('SUPABASE_URL')!
const cors={'access-control-allow-origin':'*','access-control-allow-headers':'content-type, authorization, apikey','access-control-allow-methods':'POST,OPTIONS'}
const J=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,'content-type':'application/json','cache-control':'no-store'}})
const enc=new TextEncoder()
async function sha(s:string){const d=await crypto.subtle.digest('SHA-256',enc.encode(s));return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function coord(req:Request,admin:any){const h=req.headers.get('authorization')||'';const t=h.startsWith('Bearer ')?h.slice(7):'';if(!t)return null;const {data,error}=await admin.auth.getUser(t);if(error||data.user?.app_metadata?.role!=='coordinator')return null;return data.user}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return J({error:'method'},405);const admin=createClient(URL,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false,autoRefreshToken:false}});try{const u=await coord(req,admin);if(!u)return J({error:'Coordinator session required'},401);const b=await req.json().catch(()=>({})),a=String(b.action||'');
if(a==='snapshot'){const {data:teams,error:te}=await admin.from('rescue_teams').select('id,name,join_code_display,checkin_minutes,leader_device_id,active,created_at').order('created_at');if(te)throw te;const {data:devices,error:de}=await admin.from('rescue_devices').select('id,team_id,rescuer_name,phone,active,mission_status,last_seen_at,last_lat,last_long,last_accuracy,battery,last_note,sos,approval_status,deployment_district,active_mission_id,joined_at,revoked_at').order('joined_at');if(de)throw de;const tm=new Map((teams||[]).map((t:any)=>[t.id,t]));const names=new Map((devices||[]).map((d:any)=>[d.id,d.rescuer_name]));return J({ok:true,teams:(teams||[]).map((t:any)=>({...t,leader_name:names.get(t.leader_device_id)||null})),devices:(devices||[]).map((d:any)=>({...d,team_name:tm.get(d.team_id)?.name||null}))})}
if(a==='photos'){const {data,error}=await admin.from('rescue_devices').select('id,profile_photo_data_url').not('profile_photo_data_url','is',null).limit(500);if(error)throw error;return J({ok:true,photos:(data||[]).map((r:any)=>({id:r.id,photo:r.profile_photo_data_url}))})}
if(a==='profile'){const id=String(b.device_id||'');const {data:d,error}=await admin.from('rescue_devices').select('*').eq('id',id).single();if(error)throw error;const {data:t}=d.team_id?await admin.from('rescue_teams').select('*').eq('id',d.team_id).maybeSingle():{data:null};const {data:missions}=await admin.from('rescue_missions').select('id,started_at,ended_at,status').eq('device_id',id).order('started_at',{ascending:false}).limit(50);const clean={...d,token_hash:undefined,pin_hash:undefined,rescuer_pin_hash:undefined,team_name:t?.name||null,is_leader:t?.leader_device_id===d.id};return J({ok:true,device:clean,missions:missions||[]})}
if(a==='activity'){const id=String(b.device_id||'');const [{data:d,error:de},{data:events,error:ee},{data:audit,error:ae},{data:msgs,error:me}]=await Promise.all([admin.from('rescue_devices').select('joined_at,approved_at,revoked_at,approval_status,mission_started_at,mission_ended_at').eq('id',id).single(),admin.from('rescue_activity_events').select('id,event_type,message,latitude,longitude,accuracy,created_at,metadata,mission_id').eq('device_id',id).order('created_at',{ascending:false}).limit(500),admin.from('rescue_device_audit').select('id,action,note,created_at').eq('device_id',id).order('created_at',{ascending:false}).limit(200),admin.from('rescue_messages').select('id,sender_type,message,priority,created_at,delivered_at,read_at,acknowledged_at').eq('device_id',id).order('created_at',{ascending:false}).limit(300)]);if(de)throw de;if(ee)throw ee;if(ae)throw ae;if(me)throw me;const timeline:any[]=[];for(const e of events||[])timeline.push({key:'event-'+e.id,type:e.event_type,label:e.event_type,message:e.message,created_at:e.created_at,latitude:e.latitude,longitude:e.longitude,accuracy:e.accuracy,mission_id:e.mission_id,source:'activity'});for(const x of audit||[])timeline.push({key:'audit-'+x.id,type:x.action,label:x.action,message:x.note,created_at:x.created_at,source:'audit'});for(const m of msgs||[])timeline.push({key:'message-'+m.id,type:m.sender_type==='rescuer'?'message_to_command':'message_from_command',label:m.sender_type==='rescuer'?'Message to Command':'Message from Command',message:m.message,priority:m.priority,created_at:m.created_at,source:'message'});if(d?.joined_at)timeline.push({key:'system-joined',type:'registered',label:'Registered',message:'Rescuer profile registered',created_at:d.joined_at,source:'system'});if(d?.approved_at)timeline.push({key:'system-approved',type:'approved',label:'Approved',message:'Approved by Rescue Command',created_at:d.approved_at,source:'system'});if(d?.revoked_at)timeline.push({key:'system-revoked',type:'revoked',label:'Moved to Inactive',message:'Rescuer access moved to inactive',created_at:d.revoked_at,source:'system'});const seen=new Set<string>();const clean=timeline.sort((x,y)=>new Date(y.created_at).getTime()-new Date(x.created_at).getTime()).filter(x=>{const k=[x.type,x.created_at,x.message||''].join('|');if(seen.has(k))return false;seen.add(k);return true});return J({ok:true,activity:clean})}
if(a==='gps_track'){const id=String(b.device_id||''),mid=b.mission_id?String(b.mission_id):null;let q=admin.from('rescue_locations').select('mission_id,recorded_at,received_at,latitude,longitude,accuracy,battery,event_type,note,uploaded_from_offline').eq('device_id',id).order('recorded_at',{ascending:true}).limit(5000);if(mid)q=q.eq('mission_id',mid);const {data,error}=await q;if(error)throw error;return J({ok:true,points:data||[]})}
if(a==='set_approval'){const id=String(b.device_id||''),status=String(b.status||'');if(!['approved','hold','revoked'].includes(status))return J({error:'Invalid status'},400);const now=new Date().toISOString(),p:any={approval_status:status};if(status==='approved')Object.assign(p,{active:true,approved_at:now,approved_by:u.id,revoked_at:null,revoked_by:null});if(status==='hold')p.active=true;if(status==='revoked')Object.assign(p,{active:false,revoked_at:now,revoked_by:u.id});const {error}=await admin.from('rescue_devices').update(p).eq('id',id);if(error)throw error;await admin.from('rescue_activity_events').insert({device_id:id,event_type:status==='approved'?'approved':status==='hold'?'hold':'revoked',message:status==='approved'?'Approved by Rescue Command':status==='hold'?'Placed on hold by Rescue Command':'Moved to inactive by Rescue Command',metadata:{actor_user_id:u.id}});return J({ok:true})}
if(a==='create_team'){const name=String(b.name||'').trim(),code=String(b.code||'').trim(),check=Math.max(1,Math.min(240,Number(b.checkin_minutes)||15));if(!name||code.length<4)return J({error:'Team name and 4+ character code required'},400);const h=await sha(code);const {data:exists}=await admin.from('rescue_teams').select('id').eq('join_code_hash',h).maybeSingle();if(exists)return J({error:'Team code already exists'},409);const {error}=await admin.from('rescue_teams').insert({name,join_code_hash:h,join_code_display:code,checkin_minutes:check,active:true});if(error)throw error;return J({ok:true})}
if(a==='move_team'){const id=String(b.device_id||''),team=String(b.team_id||'');const {error}=await admin.from('rescue_devices').update({team_id:team}).eq('id',id);if(error)throw error;await admin.from('rescue_activity_events').insert({device_id:id,event_type:'team_changed',message:'Rescuer moved to another team',metadata:{team_id:team,actor_user_id:u.id}});return J({ok:true})}
if(a==='set_leader'){const id=String(b.device_id||''),team=String(b.team_id||''),make=Boolean(b.make);const {error}=await admin.from('rescue_teams').update({leader_device_id:make?id:null}).eq('id',team);if(error)throw error;await admin.from('rescue_activity_events').insert({device_id:id,event_type:make?'leader_assigned':'leader_removed',message:make?'Assigned as team leader':'Removed as team leader',metadata:{team_id:team,actor_user_id:u.id}});return J({ok:true})}
if(a==='send_message'){const id=String(b.device_id||''),message=String(b.message||'').trim(),priority=['normal','urgent','emergency'].includes(String(b.priority))?String(b.priority):'normal';if(!message)return J({error:'Message required'},400);const {data:d}=await admin.from('rescue_devices').select('team_id').eq('id',id).single();const {error}=await admin.from('rescue_messages').insert({device_id:id,team_id:d?.team_id||null,sender_user_id:u.id,sender_type:'coordinator',message:message.slice(0,3000),priority});if(error)throw error;return J({ok:true})}
if(a==='delete_profile'){const id=String(b.device_id||'');const now=new Date().toISOString();const {data:d,error:readErr}=await admin.from('rescue_devices').select('active_mission_id').eq('id',id).single();if(readErr)throw readErr;await admin.from('rescue_teams').update({leader_device_id:null}).eq('leader_device_id',id);if(d?.active_mission_id){await admin.from('rescue_missions').update({ended_at:now,status:'ended',updated_at:now}).eq('id',d.active_mission_id)}const {error}=await admin.from('rescue_devices').update({active:false,approval_status:'revoked',revoked_at:now,revoked_by:u.id,sos:false,mission_status:'ended',mission_ended_at:now,active_mission_id:null}).eq('id',id);if(error)throw error;await admin.from('rescue_activity_events').insert({device_id:id,event_type:'revoked',message:'Moved to inactive by Rescue Command',metadata:{actor_user_id:u.id}});return J({ok:true,inactive:true})}
return J({error:'Unknown action'},400)}catch(e){console.error(e);return J({error:e instanceof Error?e.message:'Command failed'},500)}})
