const URL=Deno.env.get('SUPABASE_URL')!;
const BASE=URL+'/functions/v1/rescue-command-approved-ui-preview';
Deno.serve(async(req:Request)=>{
  if(req.method!=='GET') return new Response('method',{status:405});
  try{
    const r=await fetch(BASE,{headers:{'cache-control':'no-cache'}});
    if(!r.ok) return new Response('Command preview unavailable',{status:r.status});
    let h=await r.text();
    const patch=String.raw`
<style id="team-management-preview-v2-style">
.previewTeamBar{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin:0 0 12px}.previewPrimary,.previewSecondary{border:0;border-radius:8px;padding:10px 14px;font-weight:800;cursor:pointer}.previewPrimary{background:#0759A8;color:#fff}.previewSecondary{background:#EEF2F5;color:#17324D}.teamMoreBtn{font-size:19px!important}.teamMoreMenu{display:none;position:absolute;right:8px;top:36px;width:190px;background:#fff;color:#102A4A;border:1px solid #D9E1E8;border-radius:9px;box-shadow:0 10px 30px #0002;padding:5px;z-index:2200}.approvedTeamHead{position:relative}.approvedTeam.moreOpen .teamMoreMenu{display:block}.teamMoreMenu button{display:block;width:100%;border:0;background:#fff;color:#102A4A;padding:9px;border-radius:6px;text-align:left;font-weight:700;font-size:12px}.teamMoreMenu button:hover{background:#EEF4FF}.teamMoreMenu .danger{color:#B42318}.previewModal{position:fixed;inset:0;background:#0008;z-index:999999;display:none;align-items:center;justify-content:center;padding:16px}.previewModal.show{display:flex}.previewModalBox{width:min(460px,96vw);background:#fff;border-radius:14px;padding:18px;color:#102A4A}.previewModalBox h3{margin:0 0 12px}.previewModalBox label{display:block;font-weight:800;font-size:12px;margin:10px 0 4px}.previewModalBox input,.previewModalBox select{width:100%;padding:10px;border:1px solid #CBD5E1;border-radius:8px}.previewCode{font-family:monospace;background:#EEF4F1;border-radius:7px;padding:10px;font-weight:900;word-break:break-all}.previewNote{margin-top:8px;font-size:11px;color:#667085}.previewActions{display:flex;justify-content:flex-end;gap:8px;margin-top:14px}.previewToast{position:fixed;right:18px;bottom:18px;background:#102A4A;color:#fff;padding:10px 14px;border-radius:9px;z-index:9999999;display:none}.previewToast.show{display:block}
</style>
<div id="previewTeamModal" class="previewModal"><div class="previewModalBox"><h3 id="previewTeamModalTitle">Create Team</h3><label>Team Name</label><input id="previewTeamName" autocomplete="off"><label>Permanent Team Code</label><div id="previewTeamCode" class="previewCode">—</div><div class="previewNote">PREVIEW ONLY — this code is generated locally and does not change production data.</div><div class="previewActions"><button id="previewCancelTeam" class="previewSecondary">Cancel</button><button id="previewSaveTeam" class="previewPrimary">Save Preview</button></div></div></div>
<div id="previewToast" class="previewToast"></div>
<script id="team-management-preview-v2-js">(function(){
const q=id=>document.getElementById(id);let mode='create',targetTeam=null;const storeKey='rescue_team_preview_v2';
function toast(t){const x=q('previewToast');if(!x)return;x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2600)}
function clean(s){return String(s||'TEAM').toUpperCase().replace(/[^A-Z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,18)||'TEAM'}
function rand(){const a='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let s='';for(let i=0;i<6;i++)s+=a[Math.floor(Math.random()*a.length)];return s}
function generate(name){return clean(name)+'-'+rand()}
function openModal(m,team){mode=m;targetTeam=team||null;q('previewTeamModalTitle').textContent=m==='rename'?'Rename Team':'Create Team';q('previewTeamName').value=team?.name||'';q('previewTeamCode').textContent=team?.join_code_display||generate(team?.name||'TEAM');q('previewTeamModal').classList.add('show');setTimeout(()=>q('previewTeamName')?.focus(),50)}
function closeModal(){q('previewTeamModal').classList.remove('show')}
q('previewCancelTeam')?.addEventListener('click',closeModal);
q('previewTeamName')?.addEventListener('input',()=>{if(mode==='create')q('previewTeamCode').textContent=generate(q('previewTeamName').value)});
q('previewSaveTeam')?.addEventListener('click',()=>{const name=q('previewTeamName').value.trim();if(!name)return toast('Team name is required');let list=[];try{list=JSON.parse(localStorage.getItem(storeKey)||'[]')}catch{}if(mode==='create'){list.push({id:'preview-'+Date.now(),name,join_code_display:q('previewTeamCode').textContent,preview:true})}else if(targetTeam){list.push({id:targetTeam.id,name,rename_from:targetTeam.name,join_code_display:targetTeam.join_code_display,preview:true})}localStorage.setItem(storeKey,JSON.stringify(list));closeModal();toast(mode==='create'?'Preview team created — production unchanged':'Preview rename saved — production unchanged')});
function teamById(id){return (window.data?.teams||[]).find(t=>String(t.id)===String(id))}
function enhance(){const main=q('approvedMain');if(!main)return;if(!q('previewTeamBar')&&document.querySelector('.approvedStats')){const bar=document.createElement('div');bar.id='previewTeamBar';bar.className='previewTeamBar';bar.innerHTML='<button id="previewCreateTeam" class="previewPrimary">+ Create Team</button><button id="previewRenameTeam" class="previewSecondary">Rename Team</button>';main.insertBefore(bar,main.firstChild);q('previewCreateTeam').onclick=()=>openModal('create');q('previewRenameTeam').onclick=()=>{const teams=(window.data?.teams||[]).filter(t=>t.active!==false);if(!teams.length)return toast('No active team');const name=prompt('Enter exact team name to rename:');const t=teams.find(x=>String(x.name).toLowerCase()===String(name||'').trim().toLowerCase());if(!t)return toast('Team not found');openModal('rename',t)}}
document.querySelectorAll('.approvedTeam').forEach(sec=>{if(sec.querySelector('.teamMoreBtn'))return;const id=sec.dataset.team,t=teamById(id),tools=sec.querySelector('.approvedTeamTools');if(!tools||!t)return;const b=document.createElement('button');b.className='teamMoreBtn';b.type='button';b.title='More team options';b.textContent='⋮';tools.appendChild(b);const m=document.createElement('div');m.className='teamMoreMenu';m.innerHTML='<button data-p-copy>Copy Team Code</button><button data-p-rename>Rename Team</button><button data-p-regen>Regenerate Team Code</button><button data-p-disable>Disable Team Code</button><button data-p-export>Export Team</button><button class="danger" data-p-archive>Archive Team</button>';sec.querySelector('.approvedTeamHead')?.appendChild(m);b.onclick=e=>{e.stopPropagation();document.querySelectorAll('.approvedTeam.moreOpen').forEach(x=>{if(x!==sec)x.classList.remove('moreOpen')});sec.classList.toggle('moreOpen')};m.querySelector('[data-p-copy]').onclick=async()=>{try{await navigator.clipboard.writeText(t.join_code_display||'');toast('Team code copied')}catch{toast('Copy unavailable')}};m.querySelector('[data-p-rename]').onclick=()=>openModal('rename',t);m.querySelector('[data-p-regen]').onclick=()=>{if(!confirm('PREVIEW ONLY: Generate a replacement code for '+t.name+'? Production will NOT change.'))return;t.join_code_display=generate(t.name);toast('Preview code regenerated: '+t.join_code_display);sec.classList.remove('moreOpen')};m.querySelector('[data-p-disable]').onclick=()=>{if(confirm('PREVIEW ONLY: Show this code as disabled? Production will NOT change.'))toast('Preview code disabled — production unchanged')};m.querySelector('[data-p-export]').onclick=()=>toast('Preview export option visible');m.querySelector('[data-p-archive]').onclick=()=>toast('Preview archive only — production unchanged')})}
document.addEventListener('click',e=>{if(!e.target.closest('.approvedTeamHead'))document.querySelectorAll('.approvedTeam.moreOpen').forEach(x=>x.classList.remove('moreOpen'))});
const obs=new MutationObserver(()=>enhance());obs.observe(document.body,{childList:true,subtree:true});setTimeout(enhance,600);
})();</script>`;
    h=h.replace('</body>',patch+'</body>');
    return new Response(h,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store','access-control-allow-origin':'*'}})
  }catch(e){console.error(e);return new Response('Command preview unavailable',{status:500})}
});
