const RAW='https://raw.githubusercontent.com/danphe1/DMT_rescue/792313d1c3ff816f650d894b8acc20c97e569f02/supabase/functions/rescue-field/index.ts'
const REG='https://fkxbohbrfotbwmqalzyw.supabase.co/functions/v1/rescue-registration-api'
let cache:Promise<string>|null=null
async function page(){if(cache)return cache;cache=(async()=>{const r=await fetch(RAW,{headers:{'cache-control':'no-cache'}});if(!r.ok)throw new Error('base field fetch '+r.status);const s=await r.text();const a='const H=String.raw`',z='`\nDeno.serve';const i=s.indexOf(a),j=s.lastIndexOf(z);if(i<0||j<0)throw new Error('base field payload missing');let h=s.slice(i+a.length,j)
h=h.replace('<label>Profile Photo</label>','<label>Profile Photo <span style="color:#c62828">*</span></label>')
for(const [id,label] of [['teamCode','Team Join Code'],['name','Full Name'],['phone','Phone'],['pin','Create Rescuer Code'],['address','Address'],['district','Deployment District'],['blood','Blood Group'],['ecName','Emergency Contact Name'],['ecPhone','Emergency Contact Phone']])h=h.replace('<label>'+label,'<label>'+label+' <span style="color:#c62828">*</span>')
h=h.replace('<input id="terms" type="checkbox"','<input id="terms" type="checkbox" required')
h=h.replace('<input id="teamCode" autocomplete="off">','<input id="teamCode" autocomplete="off" required>')
h=h.replace('<input id="name">','<input id="name" required>')
h=h.replace('<input id="phone" inputmode="tel">','<input id="phone" inputmode="tel" required>')
h=h.replace('<input id="pin" type="password" inputmode="numeric">','<input id="pin" type="password" inputmode="numeric" required minlength="4">')
h=h.replace('<input id="address">','<input id="address" required>')
h=h.replace('<select id="district">','<select id="district" required>')
h=h.replace('<select id="blood">','<select id="blood" required>')
h=h.replace('<input id="ecName">','<input id="ecName" required autocomplete="name">')
h=h.replace('<input id="ecPhone" inputmode="tel">','<input id="ecPhone" inputmode="tel" required>')
const rs=h.indexOf('async function register(){'),re=h.indexOf('async function login(){',rs);if(rs<0||re<0)throw new Error('register function missing');const fn=`async function register(){const btn=g('register');if(btn.disabled)return;try{const vals={team:g('teamCode').value.trim(),name:g('name').value.trim(),phone:g('phone').value.trim(),pin:g('pin').value.trim(),address:g('address').value.trim(),district:g('district').value,blood:g('blood').value,ecName:g('ecName').value.trim(),ecPhone:g('ecPhone').value.trim()};if(!vals.team||!vals.name||!vals.phone||!vals.pin||!vals.address||!vals.district||!vals.blood||!vals.ecName||!vals.ecPhone)throw Error('Please complete every required field.');if(!photo)throw Error('Profile photo is required. Take a photo before submitting.');if(!/^[\\p{L}\\s]+$/u.test(vals.ecName))throw Error('Emergency contact name can contain letters and spaces only.');await gate();btn.disabled=true;btn.textContent='Sending request…';const d=await call('${REG}',{team_code:vals.team,name:vals.name,phone:vals.phone,pin:vals.pin,address:vals.address,deployment_district:vals.district,blood_group:vals.blood,emergency_contact_name:vals.ecName,emergency_contact_phone:vals.ecPhone,profile_photo_data_url:photo,device_label:navigator.userAgent.slice(0,100),tracking_terms_accepted:true,location_permission_confirmed:true});cfg={token:d.device_token,device_id:d.device_id,team:d.team};save();show('pending');g('pendingText').textContent=d.message||'Request sent — waiting for Command approval.';poll(1500)}catch(e){say('authMsg',e.message,true);btn.disabled=false;btn.textContent='Submit for Approval'}}\n`;h=h.slice(0,rs)+fn+h.slice(re)
const extra=`<script>(function(){const e=document.getElementById('ecName');if(e)e.addEventListener('input',()=>{e.value=e.value.replace(/[^\\p{L}\\s]/gu,'')});const b=document.getElementById('register');if(b)b.addEventListener('dblclick',ev=>ev.preventDefault());})();<\/script>`;return h.replace('</body>',extra+'</body>')})();try{return await cache}catch(e){cache=null;throw e}}
Deno.serve(async req=>{if(req.method!=='GET')return new Response('method',{status:405});try{return new Response(await page(),{headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store','access-control-allow-origin':'*'}})}catch(e){console.error(e);return new Response('Rescuer page temporarily unavailable',{status:500})}})
