const URL=Deno.env.get('SUPABASE_URL')!, BASE=URL+'/functions/v1/rescue-field-core-v20'
let cache:Promise<string>|null=null
async function page(){if(cache)return cache;cache=(async()=>{const r=await fetch(BASE,{headers:{'cache-control':'no-cache'}});if(!r.ok)throw new Error('base '+r.status);let h=await r.text();
const patch=String.raw`<style id="reg-alert-tutorial-style">
#regSubmitAlert{position:fixed;inset:0;background:rgba(0,0,0,.42);backdrop-filter:blur(2px);-webkit-backdrop-filter:blur(2px);z-index:999999;display:none;align-items:center;justify-content:center;padding:20px;color:#fff;text-align:center}#regSubmitAlert.show{display:flex}.regAlertBox{max-width:760px;width:min(92vw,760px);background:rgba(18,24,21,.74);border:2px solid rgba(255,255,255,.35);border-radius:22px;padding:30px 22px;box-shadow:0 20px 70px rgba(0,0,0,.35);text-align:center}.regAlertBig{font-size:clamp(30px,8vw,58px);font-weight:1000;line-height:1.05;color:#fff;text-transform:uppercase;text-align:center}.regAlertGps{font-size:clamp(27px,7vw,50px);font-weight:1000;line-height:1.08;color:#ffe45c;margin-top:20px;text-align:center}.regAlertSub{font-size:clamp(16px,4vw,21px);line-height:1.5;margin-top:20px;text-align:center;color:#fff}.regPulse{width:18px;height:18px;background:#ff3b30;border-radius:50%;display:inline-block;margin-right:8px;animation:regPulse 1s infinite}@keyframes regPulse{50%{opacity:.25;transform:scale(.7)}}
#tutorialBtn{position:fixed;right:14px;bottom:16px;z-index:9000;border:0;border-radius:999px;padding:12px 16px;background:#078346;color:#fff;font-weight:900;box-shadow:0 4px 18px #0003;cursor:pointer}#tutorialModal{position:fixed;inset:0;background:#0008;z-index:99990;display:none;align-items:center;justify-content:center;padding:14px}#tutorialModal.show{display:flex}.tutorialBox{width:min(720px,100%);max-height:90vh;overflow:auto;background:#fff;border-radius:18px;padding:18px;color:#17211b;box-shadow:0 20px 60px #0006}.tutorialTop{display:flex;align-items:center;justify-content:space-between;gap:10px;position:sticky;top:-18px;background:#fff;padding:12px 0 8px;z-index:2}.tutorialClose{background:#edf4ef;color:#244234;border:0;border-radius:9px;padding:9px 12px;font-weight:900}.tutorialStep{display:grid;grid-template-columns:42px 1fr;gap:10px;padding:12px 0;border-top:1px solid #e4ebe6}.tutorialNo{width:36px;height:36px;border-radius:50%;display:flex;align-items:center;justify-content:center;background:#078346;color:#fff;font-weight:1000}.tutorialWarn{background:#fff4d9;border:2px solid #f9a825;border-radius:12px;padding:12px;margin-top:10px}.tutorialDanger{background:#fff0f0;border:2px solid #c62828;border-radius:12px;padding:12px;margin-top:10px;font-weight:900}.biNe{font-size:.9em;color:#526159;font-weight:700}.biSlash{color:#87928b;padding:0 3px}.biLabel{display:block;font-weight:700;margin-bottom:4px}
</style>
<div id="regSubmitAlert" role="alert" aria-live="assertive"><div class="regAlertBox"><div class="regAlertBig"><span class="regPulse"></span>DO NOT CLOSE THIS BROWSER</div><div class="regAlertGps">KEEP LOCATION / GPS ON</div><div class="regAlertSub"><b>Your registration is being sent to Rescue Command.</b><br>Stay on this screen until you see <b>“Request sent — waiting for Command approval.”</b></div><div class="regAlertSub" lang="ne"><b>यो ब्राउजर बन्द नगर्नुहोस्। LOCATION / GPS अन राख्नुहोस्।</b><br>“Request sent — waiting for Command approval” नदेखिएसम्म यही स्क्रिन खुला राख्नुहोस्।</div></div></div>
<button id="tutorialBtn" type="button">? How to Use</button>
<div id="tutorialModal" aria-hidden="true"><div class="tutorialBox"><div class="tutorialTop"><div><b style="font-size:22px">How to Use the Rescuer App</b><div class="small">नेपाल स्काउट उद्धार स्वयंसेवक मार्गदर्शन</div></div><button id="tutorialClose" class="tutorialClose" type="button">Close ✕</button></div>
<div class="tutorialStep"><div class="tutorialNo">1</div><div><b>Open in Chrome or Safari</b><div class="small">Avoid WhatsApp/Facebook in-app browsers. Open the registration link in your installed browser.</div></div></div>
<div class="tutorialStep"><div class="tutorialNo">2</div><div><b>Allow Location / GPS</b><div class="small">Accept location tracking and allow precise location when your phone asks. Keep GPS/location ON during rescue duty.</div></div></div>
<div class="tutorialStep"><div class="tutorialNo">3</div><div><b>Complete Registration</b><div class="small">Enter the team code, all required personal details, emergency contact, and a clear profile photo. You may use the camera or Choose Photo from Device.</div></div></div>
<div class="tutorialStep"><div class="tutorialNo">4</div><div><b>Submit and Keep the Browser Open</b><div class="small">After tapping Submit for Approval, do not close the browser or turn off location until the request-sent confirmation appears.</div></div></div>
<div class="tutorialStep"><div class="tutorialNo">5</div><div><b>Wait for Command Approval</b><div class="small">The screen will show that your request is waiting for Rescue Command approval. Do not submit a second registration.</div></div></div>
<div class="tutorialStep"><div class="tutorialNo">6</div><div><b>Login and Start Mission</b><div class="small">After approval, login using your phone number and rescuer code. Tap START MISSION only when you begin operational duty.</div></div></div>
<div class="tutorialStep"><div class="tutorialNo">7</div><div><b>Keep GPS Running</b><div class="small">Leave location enabled. When internet is lost, captured GPS points are stored on the phone and uploaded when connection returns.</div></div></div>
<div class="tutorialStep"><div class="tutorialNo">8</div><div><b>Use Mission Buttons Correctly</b><div class="small"><b>I AM SAFE</b> confirms safety. <b>RETURNING</b> tells Command you are returning. Hold <b>SOS</b> for 3 seconds only for a real emergency. Use <b>END MISSION</b> when duty is finished.</div></div></div>
<div class="tutorialWarn"><b>Battery:</b> keep the phone charged or connected to a power bank during long deployments.</div><div class="tutorialDanger">🆘 SOS is an emergency alert. Do not test it on a real rescuer account.</div>
</div></div>
<script>(function(){const q=id=>document.getElementById(id),modal=q('tutorialModal'),open=q('tutorialBtn'),close=q('tutorialClose'),alert=q('regSubmitAlert');
function bilingualLabel(id,en,ne){const el=q(id);if(!el)return;const lab=el.closest('label')||document.querySelector('label[for="'+id+'"]');if(!lab||lab.dataset.bi)return;while(lab.firstChild&&lab.firstChild!==el)lab.removeChild(lab.firstChild);const title=document.createElement('span');title.className='biLabel';title.innerHTML=en+' <span class="biSlash">/</span> <span class="biNe" lang="ne">'+ne+'</span> <span style="color:#c62828">*</span>';lab.insertBefore(title,el);lab.dataset.bi='1'}
function applyBilingual(){[['teamCode','Team Join Code','टोली जडान कोड'],['name','Full Name','पूरा नाम'],['phone','Phone','फोन नम्बर'],['pin','Create Your Own Rescuer Code','आफ्नो उद्धारक कोड आफैं बनाउनुहोस्'],['address','Address','ठेगाना'],['district','Deployment District','परिचालन जिल्ला'],['blood','Blood Group','रक्त समूह'],['ecName','Emergency Contact Name','आपतकालीन सम्पर्क व्यक्तिको नाम'],['ecPhone','Emergency Contact Phone','आपतकालीन सम्पर्क फोन नम्बर']].forEach(x=>bilingualLabel(x[0],x[1],x[2]));const photo=[...document.querySelectorAll('label')].find(x=>/^Profile Photo/i.test(x.textContent||''));if(photo&&!photo.dataset.bi){photo.innerHTML='Profile Photo <span class="biSlash">/</span> <span class="biNe" lang="ne">प्रोफाइल फोटो</span> <span style="color:#c62828">*</span>';photo.dataset.bi='1'}const terms=q('terms')?.closest('label');if(terms&&!terms.dataset.bi){const s=terms.querySelector('span');if(s)s.innerHTML='I accept operational location tracking. <span class="biSlash">/</span> <span class="biNe" lang="ne">म उद्धार कार्यका लागि स्थान ट्र्याकिङ स्वीकार गर्छु।</span>';terms.dataset.bi='1'}const oc=q('openCam');if(oc&&/Open Camera/i.test(oc.textContent||''))oc.textContent='Open Camera / क्यामेरा खोल्नुहोस्';const cp=q('choosePhoto');if(cp&&/Choose Photo from Device/i.test(cp.textContent||''))cp.textContent='Choose Photo from Device / फोनबाट फोटो छान्नुहोस्';const rb=q('register');if(rb){const t=String(rb.textContent||'').trim();if(t==='Submit for Approval')rb.textContent='Submit for Approval / स्वीकृतिका लागि पठाउनुहोस्';else if(/^Sending request/i.test(t)&&!t.includes('/'))rb.textContent='Sending request… / अनुरोध पठाइँदैछ…'}const pending=q('pendingText');if(pending&&/Request sent/i.test(pending.textContent||'')&&!pending.dataset.bi){pending.insertAdjacentHTML('beforeend','<br><span class="biNe" lang="ne">अनुरोध पठाइयो — कमाण्डको स्वीकृतिको प्रतीक्षामा।</span>');pending.dataset.bi='1'}}
applyBilingual();const biObs=new MutationObserver(()=>applyBilingual());biObs.observe(document.body,{childList:true,subtree:true,characterData:true});
function showTutorial(){modal?.classList.add('show');modal?.setAttribute('aria-hidden','false')}function hideTutorial(){modal?.classList.remove('show');modal?.setAttribute('aria-hidden','true')}open?.addEventListener('click',showTutorial);close?.addEventListener('click',hideTutorial);modal?.addEventListener('click',e=>{if(e.target===modal)hideTutorial()});
const btn=q('register');if(btn){const obs=new MutationObserver(()=>{const sending=btn.disabled&&/sending request/i.test(btn.textContent||'');alert?.classList.toggle('show',!!sending)});obs.observe(btn,{attributes:true,childList:true,subtree:true,characterData:true});document.addEventListener('visibilitychange',()=>{if(document.hidden&&alert?.classList.contains('show')){try{navigator.vibrate?.([200,100,200])}catch{}}});}
const pending=q('pendingText');if(pending){const po=new MutationObserver(()=>{if(/request sent|waiting for coordinator approval/i.test(pending.textContent||''))alert?.classList.remove('show')});po.observe(pending,{childList:true,subtree:true,characterData:true})}
})();</script>`;
return h.replace('</body>',patch+'</body>')})();try{return await cache}catch(e){cache=null;throw e}}
Deno.serve(async req=>{if(req.method!=='GET')return new Response('method',{status:405});try{return new Response(await page(),{headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store','access-control-allow-origin':'*'}})}catch(e){console.error(e);return new Response('Rescuer page temporarily unavailable',{status:500})}})
