import { createClient } from 'npm:@supabase/supabase-js@2.102.0'
const URL=Deno.env.get('SUPABASE_URL')!
const admin=createClient(URL,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false,autoRefreshToken:false}})
const cors={'access-control-allow-origin':'*','access-control-allow-headers':'content-type, apikey, authorization','access-control-allow-methods':'POST,OPTIONS','content-type':'application/json'}
const enc=new TextEncoder()
const out=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:cors})
async function sha(s:string){const d=await crypto.subtle.digest('SHA-256',enc.encode(s));return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,'0')).join('')}
function token(){const a=new Uint8Array(32);crypto.getRandomValues(a);return [...a].map(b=>b.toString(16).padStart(2,'0')).join('')}
function phoneKey(v:any){return String(v||'').replace(/\D/g,'')}
function photo(v:any){const s=String(v||'');return s.startsWith('data:image/')&&s.length>100&&s.length<700000?s:null}
function letters(v:string){return /^[\p{L}\s]+$/u.test(v)}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return out({ok:false,error:'method'},405);try{const b=await req.json();const code=String(b.team_code||'').trim(),name=String(b.name||'').trim(),phone=String(b.phone||'').trim(),pin=String(b.pin||'').trim(),address=String(b.address||'').trim(),district=String(b.deployment_district||'').trim(),blood=String(b.blood_group||'').trim(),ecName=String(b.emergency_contact_name||'').trim(),ecPhone=String(b.emergency_contact_phone||'').trim(),p=photo(b.profile_photo_data_url),label=String(b.device_label||'').slice(0,120)||null;const pk=phoneKey(phone),epk=phoneKey(ecPhone)
if(!code||!name||!phone||!pin||!address||!district||!blood||!ecName||!ecPhone||!p)return out({ok:false,error:'All registration fields, including profile photo, are required.'},400)
if(name.length<2)return out({ok:false,error:'Enter your full name.'},400)
if(pk.length<7||pk.length>15)return out({ok:false,error:'Enter a valid phone number.'},400)
if(epk.length<7||epk.length>15)return out({ok:false,error:'Enter a valid emergency contact phone number.'},400)
if(pin.length<4)return out({ok:false,error:'Rescuer code must be at least 4 digits.'},400)
if(!letters(ecName))return out({ok:false,error:'Emergency contact name can contain letters and spaces only.'},400)
if(b.tracking_terms_accepted!==true||b.location_permission_confirmed!==true)return out({ok:false,error:'Location tracking consent and location permission are required.'},400)
const ch=await sha(code);const {data:team,error:te}=await admin.from('rescue_teams').select('id,name,checkin_minutes,active').eq('join_code_hash',ch).eq('active',true).maybeSingle();if(te)throw te;if(!team)return out({ok:false,error:'Invalid team code.'},403)
const {data:all,error:ae}=await admin.from('rescue_devices').select('id,team_id,rescuer_name,phone,rescuer_pin_hash,active,approval_status,mission_status').not('phone','is',null).limit(5000);if(ae)throw ae;const existing=(all||[]).find((d:any)=>phoneKey(d.phone)===pk)
if(existing){if(existing.approval_status==='revoked'||existing.active===false)return out({ok:false,already_registered:true,approval_status:existing.approval_status,error:'This rescuer is already registered but inactive/revoked. Contact Rescue Command instead of registering again.'},409);if(existing.rescuer_pin_hash!==await sha(pin))return out({ok:false,already_registered:true,approval_status:existing.approval_status,error:'This phone number is already registered. Use Rescuer Login with the original rescuer code.'},409);const raw=token();await admin.from('rescue_devices').update({token_hash:await sha(raw),last_seen_at:new Date().toISOString(),device_label:label}).eq('id',existing.id);const {data:t}=await admin.from('rescue_teams').select('id,name,checkin_minutes').eq('id',existing.team_id).maybeSingle();return out({ok:true,already_registered:true,pending:existing.approval_status!=='approved',approval_status:existing.approval_status,mission_status:existing.mission_status,device_id:existing.id,device_token:raw,team:t,message:existing.approval_status==='pending'?'Request already sent — waiting for Command approval.':existing.approval_status==='hold'?'Registration is on hold. Please wait for Command.':'Already registered and approved. Use Rescuer Login.'})}
const raw=token(),now=new Date().toISOString();const {data:dev,error}=await admin.from('rescue_devices').insert({team_id:team.id,rescuer_name:name,phone,address,blood_group:blood,emergency_contact_name:ecName,emergency_contact_phone:ecPhone,profile_photo_data_url:p,profile_updated_at:now,rescuer_pin_hash:await sha(pin),token_hash:await sha(raw),mission_status:'pending',approval_status:'pending',device_label:label,deployment_district:district,tracking_terms_accepted_at:now,tracking_terms_version:'2026-08-30-v3',location_permission_confirmed:true}).select('id').single();if(error)throw error;await admin.from('rescue_device_audit').insert({device_id:dev.id,action:'registered',note:'New rescuer registration awaiting coordinator approval'});await admin.from('rescue_activity_events').insert({device_id:dev.id,event_type:'registered',message:'New rescuer registration awaiting coordinator approval',metadata:{team_id:team.id}});return out({ok:true,pending:true,approval_status:'pending',device_id:dev.id,device_token:raw,team,message:'Request sent — waiting for Command approval.'})}catch(e){console.error(e);return out({ok:false,error:e instanceof Error?e.message:'Registration failed'},500)}})
