const RAW='https://raw.githubusercontent.com/danphe1/DMT_rescue/fix/profile-device-photo-map-2026-08-30/supabase/functions/rescue-command-center/index.ts';
let basePromise:Promise<string>|null=null;
async function basePage(){if(basePromise)return basePromise;basePromise=(async()=>{const r=await fetch(RAW,{headers:{'cache-control':'no-cache'}});if(!r.ok)throw new Error('backup fetch '+r.status);const src=await r.text();const parts=[...src.matchAll(/const C\d+='([^']+)'/g)].map(m=>m[1]);if(!parts.length)throw new Error('backup payload missing');const bytes=Uint8Array.from(atob(parts.join('')),c=>c.charCodeAt(0));const ds=new DecompressionStream('gzip');return await new Response(new Blob([bytes]).stream().pipeThrough(ds)).text()})();try{return await basePromise}catch(e){basePromise=null;throw e}}
const PATCH=String.raw`<style id="dmt-ui-patch">
#rescuerNav{position:fixed;left:0;top:76px;bottom:0;width:255px;background:#fff;border-right:1px solid #d8e5dd;z-index:900;overflow:auto;box-shadow:2px 0 8px #0001}.rescuerNavHead{position:sticky;top:0;background:#fff;padding:11px;border-bottom:1px solid #e5ece7;z-index:2}.rescuerNavList{padding:6px}.rescueSideItem{width:100%;display:grid;grid-template-columns:38px minmax(0,1fr) 10px;gap:8px;align-items:center;text-align:left;border:0;background:transparent;padding:8px;border-radius:9px;border-left:4px solid var(--tc,#087443);cursor:pointer}.rescueSideItem:hover{background:#f4f8f5}.sidePhoto,.sideFallback,.dashPhoto{width:38px;height:38px;border-radius:50%;object-fit:cover;background:#e7efea;border:2px solid var(--tc,#087443)}.sideFallback{display:grid;place-items:center;font-weight:900;color:#075d37}.sideName{font-weight:800;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.teamDot{width:9px;height:9px;border-radius:50%;background:var(--tc,#087443)}#app.dmtSidebar{margin-left:265px}.dmtMenuBtn{display:none}.team{border-left:6px solid var(--tc,#087443)!important}.teamhead{background:var(--tb,#f2f7f4)!important}.member{grid-template-columns:46px minmax(155px,1.3fr) 120px 110px minmax(225px,1fr)!important}.dashPhotoFallback{width:38px;height:38px;border-radius:50%;display:grid;place-items:center;background:#e7efea;color:#075d37;font-weight:900;border:2px solid var(--tc,#087443)}.photoSkeleton{animation:dmtPulse 1.2s ease-in-out infinite}@keyframes dmtPulse{50%{opacity:.45}}
@media(max-width:1050px) and (min-width:801px){#rescuerNav{width:220px}#app.dmtSidebar{margin-left:230px}.member{grid-template-columns:46px minmax(130px,1fr) 105px 95px!important}.member>div:last-child{grid-column:2/-1}}
@media(max-width:800px){body{overflow-x:hidden}.top{padding:7px 8px}.top .logo{width:42px;height:42px}.top .brand>div{min-width:0}.top .brand b{font-size:14px}.top .brand div div{display:none}.dmtMenuBtn{display:inline-block!important;flex:0 0 auto}#app.dmtSidebar{margin-left:0}#rescuerNav{top:0;z-index:4000;width:min(86vw,320px);transform:translateX(-105%);transition:transform .2s ease;box-shadow:3px 0 18px #0004}#rescuerNav.open{transform:translateX(0)}#dmtBackdrop{display:none;position:fixed;inset:0;background:#0008;z-index:3900}#dmtBackdrop.open{display:block}.wrap{padding:7px}.stats{grid-template-columns:1fr 1fr!important}.toolbar{grid-template-columns:1fr!important}.layout{grid-template-columns:1fr!important}.member{grid-template-columns:46px minmax(0,1fr)!important;gap:7px!important}.member>div:nth-child(2){grid-column:2}.member>div:nth-child(3),.member>div:nth-child(4){grid-column:2}.member>div:nth-child(5){grid-column:1/-1;display:flex;gap:6px;flex-wrap:wrap}.member>div:nth-child(5) .btn{flex:1 1 42%;min-width:110px}.teamhead{flex-direction:column;align-items:flex-start}.map{height:300px!important}.modal{padding:0!important;place-items:stretch!important}.modalbox{width:100%!important;height:100vh!important;max-height:100vh!important;border-radius:0!important;padding:10px!important}.profileTop{grid-template-columns:1fr!important}.profilePhoto,.profilePhotoFallback{width:120px!important;height:120px!important}.grid{grid-template-columns:1fr!important}.row>select{max-width:100%!important}.row>.btn{flex:1 1 42%}.login{margin:28px 7px!important}}
</style><script id="dmt-ui-patch-js">
(function(){
const TEAM_COLORS=['#087443','#175cd3','#7a3e9d','#c25a15','#007a78','#9a6700','#c12b5a','#4c6b22'];let photoMap=new Map(),photosLoaded=false;
function colorFor(id){let h=0,s=String(id||'team');for(let i=0;i<s.length;i++)h=((h<<5)-h+s.charCodeAt(i))|0;return TEAM_COLORS[Math.abs(h)%TEAM_COLORS.length]}
function tint(hex){const n=parseInt(hex.slice(1),16),r=(n>>16)&255,g=(n>>8)&255,b=n&255;return 'rgba('+r+','+g+','+b+',.08)'}
function ini(n){return String(n||'?').trim().split(/\s+/).map(x=>x[0]||'').join('').slice(0,2).toUpperCase()}
function photoHtml(d,cls){const c=colorFor(d.team_id),p=photoMap.get(d.id);return p?'<img class="'+cls+'" style="--tc:'+c+'" src="'+E(p)+'" alt="'+E(d.rescuer_name)+'">':'<div class="'+(cls==='sidePhoto'?'sideFallback':'dashPhotoFallback')+'" style="--tc:'+c+'">'+E(ini(d.rescuer_name))+'</div>'}
function closeSide(){document.getElementById('rescuerNav')?.classList.remove('open');document.getElementById('dmtBackdrop')?.classList.remove('open')}
function renderSide(){const box=document.getElementById('rescuerNavList');if(!box)return;const q=(document.getElementById('dmtSideSearch')?.value||'').toLowerCase();const list=(data.devices||[]).filter(d=>!q||[d.rescuer_name,d.phone,d.team_name,d.deployment_district].some(v=>String(v||'').toLowerCase().includes(q)));document.getElementById('dmtSideCount').textContent=list.length+' rescuers';box.innerHTML=list.map(d=>{const c=colorFor(d.team_id);return '<button class="rescueSideItem" style="--tc:'+c+'" data-dmt-profile="'+d.id+'">'+photoHtml(d,'sidePhoto')+'<span><span class="sideName">'+E(d.rescuer_name)+'</span><span class="small" style="display:block">'+E(d.team_name||'Unassigned')+' • '+(live(d)?'LIVE':'offline')+'</span></span><span class="teamDot" style="--tc:'+c+'"></span></button>'}).join('')||'<div class="small" style="padding:10px">No rescuers found.</div>'}
function enhanceDashboard(){const teams=[...document.querySelectorAll('#teams .team')];teams.forEach((el,i)=>{const t=data.teams[i];if(!t)return;const c=colorFor(t.id);el.style.setProperty('--tc',c);el.style.setProperty('--tb',tint(c))});document.querySelectorAll('#teams .member').forEach(row=>{const b=row.querySelector('[data-profile]'),id=b?.dataset.profile,d=(data.devices||[]).find(x=>x.id===id);if(!d)return;const c=colorFor(d.team_id);row.style.setProperty('--tc',c);let slot=row.querySelector('.dmtDashPhoto');if(!slot){slot=document.createElement('div');slot.className='dmtDashPhoto';row.insertBefore(slot,row.firstChild)}slot.innerHTML=photoHtml(d,'dashPhoto')})}
async function loadPhotos(){if(photosLoaded)return;try{const r=await api('photos');photoMap=new Map((r.photos||[]).map(x=>[x.id,x.photo]));photosLoaded=true;enhanceDashboard();renderSide()}catch(e){console.warn('photo load',e)}}
function install(){if(document.getElementById('rescuerNav'))return;const app=document.getElementById('app');if(!app)return;app.classList.add('dmtSidebar');const nav=document.createElement('aside');nav.id='rescuerNav';nav.innerHTML='<div class="rescuerNavHead"><b>Rescuers</b><div id="dmtSideCount" class="small">Loading…</div><input id="dmtSideSearch" placeholder="Search rescuers" style="margin-top:8px"></div><div id="rescuerNavList" class="rescuerNavList"></div>';document.body.appendChild(nav);const bd=document.createElement('div');bd.id='dmtBackdrop';document.body.appendChild(bd);const btn=document.createElement('button');btn.id='dmtMenuBtn';btn.className='btn white dmtMenuBtn';btn.textContent='☰ Rescuers';document.querySelector('.top .brand')?.prepend(btn);btn.onclick=()=>{nav.classList.add('open');bd.classList.add('open')};bd.onclick=closeSide;document.getElementById('dmtSideSearch').oninput=renderSide;document.addEventListener('click',e=>{const x=e.target.closest('[data-dmt-profile]');if(x){closeSide();openProfile(x.dataset.dmtProfile).catch(er=>alert(er.message))}});const originalRender=render;render=function(){originalRender();enhanceDashboard();renderSide();if(!photosLoaded)setTimeout(loadPhotos,0)};enhanceDashboard();renderSide();if(!photosLoaded)setTimeout(loadPhotos,0)}
install();
})();
</script>`;
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:{'access-control-allow-origin':'*'}});if(req.method!=='GET')return new Response('method',{status:405});try{const h=await basePage();return new Response(h.replace('</body>',PATCH+'</body>'),{headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store','access-control-allow-origin':'*'}})}catch(e){console.error(e);return new Response('Command temporarily unavailable',{status:500})}});